### ISSUE TITLE
ltex_extra with grammar guard

### ISSUE THREAD

**Issue by Whelagen** [barreiroleo/ltex_extra.nvim#15]
I try ltex_extra with grammar-guard.
Because ltex_extra don't find any ltex server, I'll have to add "grammar_guard" in order ltex_extra can deal with ltex server.
this is the rewrite catch_ltex function :
```
local function catch_ltex()
    log.trace("catch_ltex")
    local buf_clients = vim.lsp.buf_get_clients()
    local client = nil
    for _, lsp in pairs(buf_clients) do
        if lsp.name == "ltex" or lsp.name == "grammar_guard" then client = lsp end
    end
    return client
end
```

**Comment by barreiroleo** [comment]
Hello @Whelagen, I hope you're well.

If `ltex_extra` can't find `ltex` server is because you have an issue with your server attachment process.
I just support lsp-config and mason installer.

I'm not going to support installation by `grammar_guard` because is an inactive project and not necessary today. Check [#6](https://github.com/brymer-meneses/grammar-guard.nvim/issues/6#issue-1055869776)

Regards!

**Comment by Whelagen** [comment]
Thanks for this help.
I have remove grammar guard, and just attach the lsp_ls correctly.
I'm able to use ltex_extra with my latex file on Neovim.
Best regards !
Whelagen
