### ISSUE TITLE
Incorrect buffer for code actions with lspsaga

### ISSUE THREAD

**Issue by HawkinsT** [barreiroleo/ltex_extra.nvim#17]
**Describe the bug**
As mentioned previously in https://github.com/barreiroleo/ltex_extra.nvim/issues/7#issuecomment-1193248803 ltex_extra throws `error catching ltex client` when code actions are executed via the lspsaga menu. Is it possible to investigate this further, or add a note to the readme to say that this doesn't work with lspsaga?

**Comment by barreiroleo** [comment]
Hello @HawkinsT,
I'd added this to the readme. Unfortunately is a lower priority for me because I'm not using lspsaga and require some time to read the plugin's architecture.

The PRs are very welcome, in the meantime, I think you can use code action through the native `vim.lsp.buf.code_action`.

**Comment by HawkinsT** [comment]
Hi @barreiroleo, thanks a lot for that! If I get the time in a few weeks I'll take a look (although no guarantees it's something I'll be able to fix).

**Comment by ericyuxuanye** [comment]
First of all, thank you for this amazing plugin! I was using Lspsaga and I ran into the same issue. I think the reason is that Lspsaga opens its floating windows with the filetype `markdown`, which in turn activates ltex. I removed `markdown` from the `filetypes` field in `setup` and added the following autocommand:

```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = "markdown",
    callback = function()
        if vim.api.nvim_win_get_config(0).relative == "" then
            vim.cmd("LspStart ltex")
        end
    end
})
```

This would activate ltex only if the window is not floating. So far, this seems to work, as long as you don't need ltex inside floating windows.
