### ISSUE TITLE
Attempt to index field ltex (nil value)

### ISSUE THREAD

**Issue by ghostbuster91** [barreiroleo/ltex_extra.nvim#22]
**Describe the bug**
An error occurs when initializing buffer with following message:
```
Attempt to index field ltex (nil value)
```
It only shows if I don't pass the settings object during the initialization of the LSP.

**To Reproduce**
Configure lsp in following way:
```
lspconfig.ltex.setup {
    capabilities = capabilities,
    on_attach = function(client, bufnr)
        require("ltex_extra").setup {
            load_langs = { "pl-PL", "en-US" },
            init_check = true,
            path = "./.dict",
            log_level = "none",
        }
    end
}
```
and open a file in vim that would trigger ltex to be attached, e.g. `.md`.
The error shows up.

When I add 
```
    settings = {
        ltex = {
            -- your settings.
        }
    }
```
to the `ltex.setup` call the error goes away.

**Expected behavior**
I think that the error should not happen when not passing the empty `settings` object.

**Screenshots**

**System:**
 - OS: linux
 - Neovim version: 0.8.1
 - LTeX server intallation method: vim-plug

![ltex](https://user-images.githubusercontent.com/5662622/210864523-f50327b4-9530-42e8-9710-f647725070af.gif)

Update: fix invalid comments in code snippets

**Comment by barreiroleo** [comment]
Hello @ghostbuster91,

The segment is the `lspconfig` config for Ltex, it's not my scope. Check out how lspconfig works and also inspect in provided ltex settings for what you can override or which options there are as defaults: [ltex.lua](https://github.com/neovim/nvim-lspconfig/blob/700eda91316a876757bf306fd709fde75aadb36a/lua/lspconfig/server_configurations/ltex.lua), [server config](https://github.com/neovim/nvim-lspconfig/blob/e69978a39e4d3262b09ce6a316beff384f443e3b/doc/server_configurations.txt#ltex)

The suggested mechanism is to attach ltex_extra when ltex is called.
You can invent the method that you want to attach the plugin, but I recommend and support this way.

Also, check the way of the comments In lua: ` load_langs = { "pl-PL", "en-US" }, -- dictionaries will be loaded` instead of `load_langs = { "pl-PL", "en-US" },dictionaries will be loaded`

Regards

**Comment by ghostbuster91** [comment]
Thanks for the reply. 

Regarding the comments - I don't know how that happened but it seems that I made a mistake when I was striping down the minimal setup from them. Anyway, in my code I have them specified correctly.

Thanks for the links to the server, I will check them out. 

Regarding the issue, I understand that this segmenet is from `lspconfig` for Ltex, but I don't understand why not providing it is causing an error in `ltex_extra` plugin. As you can see, I am initializing `ltex_extra` in `on_attach` callback for the ltex language server.

**Comment by barreiroleo** [comment]
I did a fast test and get the same error.
The line where there is a bug is related to the compatibility with hardcoded dictionary words. I need to set a higher level of logging and check what is changed in the client table settings.

I wish to do a refactor with the architecture first, there are a couple of things that I don't like about the design.
So, I'm not going to fix this very soon because I don't have much time. PRs are very welcome.

**Comment by ghostbuster91** [comment]
Sure that is understandable. 
It is not a big issue for me, I just wanted to report it as a good citizen :)
I am happy to wait for the architecture rewrite or someone else fixing that as I also don't have much time unfortunately.

**Comment by barreiroleo** [comment]
Thank you, I really appreciate it I hope the plugin was useful for you.

**Comment by ghostbuster91** [comment]
Totally, apart from this little issue it works like a charm! Thanks for creating it :)

**Comment by barreiroleo** [comment]
A pleasure to hear it, the bug was resolved btw. Cheers!
