### ISSUE TITLE
User dictionary not loaded

### ISSUE THREAD

**Issue by philip1987** [barreiroleo/ltex_extra.nvim#7]
Hey thank you for your cool plugin!

### Issue
I am able to add words to a user dictionary, but I cannot load them from the dictionary  when I restart neovim.
Not sure if your plugin supports loading dictionaries, or not.
As far as I know ltex-ls does not support user dictionaries.

### Questions
1. Does your plugin support the loading of user dictionaries? 
2. If yes, how can I configure it?
3. If not, do you plan on adding it?

If you need more information or something is not clear, let me know.
Thanks again for your amazing work!

**Comment by barreiroleo** [comment]
Hey @philip1987, I appreciate that you like the plugin!

If you can add words to a dictionary successfully, you should be able to load at the restart. Check that the variable `init_check` is true and the `path` is correct on your settings.

The expected behaviour is as shown in the demo https://github.com/barreiroleo/ltex_extra.nvim#autoload-exported-data.

The plugin admits the same custom dictionaries that use the official plugin (naming and content). In addition, you can define a path in settings for using global dictionaries or per project dictionaries (using relatives or absolute paths).

If you want to write your dictionaries, I recommend you recycle one generated with ltex_extra code actions to guarantee that naming and structure are correct.

If you are referring to using vim's built-in dictionary, there is a snippet to autoload in ltex. It's unsupported by ltex_extra at this time.
Ltex_extra reads the files content and notifies ltex that these are the words to use, overwriting the previous definitions. If someone wants this feature, I could work on it.

**Comment by philip1987** [comment]
Thank you for your quick reply! I managed to get it to work (It turned out to be an error in my config that caused the following error: "Error catching ltex client"). With this error gone, ltex-extra is now picking up the dictionary on reload. Having useful spell- and grammar check in my neovim (as opposed to the crude built-in spellcheck from vim) is a major boost in my productivity!

**Comment by thiag0mei** [comment]
Hi, philip1987, I am also getting a 'Error catching ltex client' on my config. What happened in yours?

**Comment by barreiroleo** [comment]
> Thank you for your quick reply! I managed to get it to work (It turned out to be an error in my config that caused the following error: "Error catching ltex client"). With this error gone, ltex-extra is now picking up the dictionary on reload. Having useful spell- and grammar check in my neovim (as opposed to the crude built-in spellcheck from vim) is a major boost in my productivity!

It's nice to read that, cheers!

**Comment by barreiroleo** [comment]
> Hi, philip1987, I am also getting a 'Error catching ltex client' on my config. What happened in yours?

Hey @thiag0mei, this error means the plugin cannot talk with the LTeX server. When this occurs, it very often is because LTeX it's not running. You can run :LspInfo and check the clients attached to the buffer.

Check the recommendations in Configuration section (https://github.com/barreiroleo/ltex_extra.nvim#configuration). This way guarantee call Ltex_extra when LTeX is starting up.

**Comment by thiag0mei** [comment]
@barreiroleo, in my case the error occurs when the plugin tries to update after triggering any code action. The terms are added to the proper files and I can reload manually with reload() but auto-reloading does not work.

**Comment by barreiroleo** [comment]
Please, share your lspconfig and ltex settings...

**Comment by thiag0mei** [comment]
I believe I might have narrowed it down. I use lspsaga for a code action "window" which creates a new buffer and it looks like ltex_extra is looking for the client in that buffer thus resulting in the error.

Logs:
```
Executing CursorMoved Autocommands for "<buffer=3>"
autocommand <lua: 303>

Error catching ltex client
Executing BufLeave Autocommands for "*"
autocommand if &ft != "netrw"|let w:netrw_prvfile= expand("%:p")|endif
```

:LspInfo with the codeaction window open
```
 Language client log: /home/thiago/.cache/nvim/lsp.log
 Detected filetype:   sagacodeaction
 
 0 client(s) attached to this buffer: 
 
 2 active client(s) not attached to this buffer: 
 
 Client: ltex (id: 1, pid: 4615, bufnr: [1])
 	filetypes:       bib, gitcommit, markdown, org, plaintex, rst, rnoweb, tex
 	autostart:       true
 	root directory:  /home/thiago/Documents/docs
 	cmd:             ltex-ls
```

I might just stop using lspsaga for this purpose then, and use the built-in function instead.

**Comment by barreiroleo** [comment]
Ltex looks for clients on the buffer that called the code action. It looks like `lspsaga` is capturing the `buf.execute_command` and he does the call. It would surprise me because I was using a similar method before and on neovim 0.72 it started to fail.

Unfortunately, I don't use lspsaga and neither have enough trace logs on catching steps to look for a change in bufnr ID. I should research how lspsaga works. Maybe I could mark the buffer on the start sequence, but I don't know how it affects to multi buffer operation.

I'm sorry for can't give you a favourable answer at this moment.

**Comment by philip1987** [comment]
@thiag0mei I think your case might be different than mine, as I was getting the

**Comment by philip1987** [comment]
@thiag0mei In my case, I didn't pass the 'client' and 'bufnr' parameters to the on_attach function.  All the other language servers in my config don't need those parameters. Here's how I solved the error: I have two different on_attach functions defined, one generic, that doesn't require the 'client' and 'bufnr' parameters and one specific for ltex-ls that I called 'on_ltex_attach'. Here are some relevant snipppets from my config that I have annotated with comments for you:

```lua
-- My generic on_attach function without any parameters
local on_attach = function()
    vim.keymap.set("n", "gd", vim.lsp.buf.definition, { buffer = 0 })
    vim.keymap.set("n", "gt", vim.lsp.buf.type_definition, { buffer = 0 })
    ...
end
```

```lua
-- My on_ltex_attach function for ltex-ls in which I configure my ltex-extra settings
local on_ltex_attach = function(client, bufnr) -- if client is not defined here you get 'Error catching ltex client'
    local ok, ltex_extra = pcall(require, "ltex_extra") -- protected call in case ltex_extra is not installed
    if not ok then
        return
    end
    ltex_extra.setup { 
        load_langs = { "en-US" }, 
        init_check = true, -- You need this one set to true
        path = "/Users/philip/.config/nvim/spell/",
        log_level = "none",
    }
    on_attach() -- Call to the generic on_attach function so I also get my keybindings for ltex-ls
end
```

```lua
-- Logic to call the on_ltex_attach function only for the ltex-ls server. For all other servers it just calls on_attach
local attach_switcher = function(lsp)
    if lsp == "ltex" then
        return on_ltex_attach
    end
    return on_attach
end
```

```lua
-- Defining some ltex_specific settings
local ltex_settings = {
    ltex = {
        disabledRules = {
            ['en-US'] = { 'PROFANITY' }, -- Don't censor my speech :-)
        },
    }
}

local settings_switcher = function(lsp)
    if lsp == "ltex" then
        return ltex_settings
    end
end
```

```lua
-- Setting up all language servers that were installed with lsp_installer 
for _, server in ipairs(lsp_installer.get_installed_servers()) do
    lspconfig[server.name].setup({
        on_attach = attach_switcher(server.name), -- server.name is the lsp parameter in attach_switcher(lsp)
        capabilities = capabilities,
        settings = settings_switcher(server.name), -- server.name is the lsp parameter in settings(lsp)
    })
end
```
I hope this helps.
Disclaimer: I might not have gotten some things right, as I have to admit I don't fully understand how ltex-ls, ltex-extra and any other server is being setup for nvim-lsp.

**Comment by barreiroleo** [comment]
As you can probably note, I don't use client and buffrn arguments for setting up `ltex_extra`. So probably is an issue more related to the `ltex` config. Sorry for the late on answering.
